/*
 * This file is generated by jOOQ.
 */
package generated_jooq.tables.pojos;


import java.io.Serializable;


/**
 * ?????
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

    private static final long serialVersionUID = 1039989866;

    private Long   id;
    private Long   userId;
    private String roleName;
    private Long   createAt;

    public Role() {}

    public Role(Role value) {
        this.id = value.id;
        this.userId = value.userId;
        this.roleName = value.roleName;
        this.createAt = value.createAt;
    }

    public Role(
        Long   id,
        Long   userId,
        String roleName,
        Long   createAt
    ) {
        this.id = id;
        this.userId = userId;
        this.roleName = roleName;
        this.createAt = createAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public Long getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(roleName);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
