/*
 * This file is generated by jOOQ.
 */
package generated_jooq.tables.pojos;


import java.io.Serializable;


/**
 * ???
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 150310017;

    private Long    id;
    private String  name;
    private Integer age;
    private String  email;
    private Long    createAt;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.age = value.age;
        this.email = value.email;
        this.createAt = value.createAt;
    }

    public User(
        Long    id,
        String  name,
        Integer age,
        String  email,
        Long    createAt
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.email = email;
        this.createAt = createAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getCreateAt() {
        return this.createAt;
    }

    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);
        sb.append(", ").append(email);
        sb.append(", ").append(createAt);

        sb.append(")");
        return sb.toString();
    }
}
