/*
 * This file is generated by jOOQ.
 */
package generated_jooq.tables.records;


import generated_jooq.tables.User;
import generated_jooq.tables.interfaces.IUser;

import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 引导页
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record5<Long, String, Integer, String, Long>, IUser {

    private static final long serialVersionUID = -2048333370;

    /**
     * Setter for <code>jooq_flyway.user.id</code>. 主键ID
     */
    @Override
    public UserRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jooq_flyway.user.id</code>. 主键ID
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jooq_flyway.user.name</code>. 姓名
     */
    @Override
    public UserRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jooq_flyway.user.name</code>. 姓名
     */
    @Size(max = 30)
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jooq_flyway.user.age</code>. 年龄
     */
    @Override
    public UserRecord setAge(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jooq_flyway.user.age</code>. 年龄
     */
    @Override
    public Integer getAge() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>jooq_flyway.user.email</code>. 邮箱
     */
    @Override
    public UserRecord setEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jooq_flyway.user.email</code>. 邮箱
     */
    @Size(max = 50)
    @Override
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jooq_flyway.user.create_at</code>. 创建时间
     */
    @Override
    public UserRecord setCreateAt(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jooq_flyway.user.create_at</code>. 创建时间
     */
    @Override
    public Long getCreateAt() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Integer, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, Integer, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return User.USER.AGE;
    }

    @Override
    public Field<String> field4() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<Long> field5() {
        return User.USER.CREATE_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getAge();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public Long component5() {
        return getCreateAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getAge();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public Long value5() {
        return getCreateAt();
    }

    @Override
    public UserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserRecord value3(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value5(Long value) {
        setCreateAt(value);
        return this;
    }

    @Override
    public UserRecord values(Long value1, String value2, Integer value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUser from) {
        setId(from.getId());
        setName(from.getName());
        setAge(from.getAge());
        setEmail(from.getEmail());
        setCreateAt(from.getCreateAt());
    }

    @Override
    public <E extends IUser> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, String name, Integer age, String email, Long createAt) {
        super(User.USER);

        set(0, id);
        set(1, name);
        set(2, age);
        set(3, email);
        set(4, createAt);
    }
}
