/*
 * This file is generated by jOOQ.
 */
package generated_jooq.tables.interfaces;


import java.io.Serializable;

import javax.validation.constraints.Size;


/**
 * 引导页
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUser extends Serializable {

    /**
     * Setter for <code>jooq_flyway.user.id</code>. 主键ID
     */
    public IUser setId(Long value);

    /**
     * Getter for <code>jooq_flyway.user.id</code>. 主键ID
     */
    public Long getId();

    /**
     * Setter for <code>jooq_flyway.user.name</code>. 姓名
     */
    public IUser setName(String value);

    /**
     * Getter for <code>jooq_flyway.user.name</code>. 姓名
     */
    @Size(max = 30)
    public String getName();

    /**
     * Setter for <code>jooq_flyway.user.age</code>. 年龄
     */
    public IUser setAge(Integer value);

    /**
     * Getter for <code>jooq_flyway.user.age</code>. 年龄
     */
    public Integer getAge();

    /**
     * Setter for <code>jooq_flyway.user.email</code>. 邮箱
     */
    public IUser setEmail(String value);

    /**
     * Getter for <code>jooq_flyway.user.email</code>. 邮箱
     */
    @Size(max = 50)
    public String getEmail();

    /**
     * Setter for <code>jooq_flyway.user.create_at</code>. 创建时间
     */
    public IUser setCreateAt(Long value);

    /**
     * Getter for <code>jooq_flyway.user.create_at</code>. 创建时间
     */
    public Long getCreateAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUser
     */
    public void from(IUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUser
     */
    public <E extends IUser> E into(E into);
}
