/*
 * This file is generated by jOOQ.
 */
package generated_jooq;


import generated_jooq.tables.Role;
import generated_jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqFlyway extends SchemaImpl {

    private static final long serialVersionUID = -1083122583;

    /**
     * The reference instance of <code>jooq_flyway</code>
     */
    public static final JooqFlyway JOOQ_FLYWAY = new JooqFlyway();

    /**
     * 全局配置表
     */
    public final Role ROLE = Role.ROLE;

    /**
     * 引导页
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private JooqFlyway() {
        super("jooq_flyway", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Role.ROLE,
            User.USER);
    }
}
