/*
 * This file is generated by jOOQ.
 */
package generated_jooq;


import generated_jooq.tables.Role;
import generated_jooq.tables.User;


/**
 * Convenience access to all tables in jooq_flyway
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * ?????
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * ???
     */
    public static final User USER = User.USER;
}
